// <auto-generated />
using System;
using HighLowGame.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HighLowGame.Infrastructure.Migrations.GameSession
{
    [DbContext(typeof(GameSessionContext))]
    partial class GameSessionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerOneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerOneScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerTwoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerTwoScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerOneId", "PlayerTwoId")
                        .IsUnique();

                    b.ToTable("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
