// <auto-generated />
using System;
using HighLowGame.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HighLowGame.Infrastructure.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    [Migration("20240203214508_AddGameContext")]
    partial class AddGameContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerOneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerOneScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerTwoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerTwoScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameSession");
                });

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.PlayerMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ChooseHigher")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberChosen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerMove");
                });

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.GameSession", b =>
                {
                    b.HasOne("HighLowGame.Infrastructure.Entities.Game", "Game")
                        .WithMany("GameSession")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.PlayerMove", b =>
                {
                    b.HasOne("HighLowGame.Infrastructure.Entities.Game", "Game")
                        .WithMany("PlayerMoves")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HighLowGame.Infrastructure.Entities.Game", b =>
                {
                    b.Navigation("GameSession");

                    b.Navigation("PlayerMoves");
                });
#pragma warning restore 612, 618
        }
    }
}
